apiVersion: v2
name: psmonit
description: A helm chart for monitoring processes running inside pods, create slack alerts if it finds any unexpected processes
type: application
version: 1.0.2
appVersion: "1.0.0"
maintainers:
  - name: Prasad Krishnan
    email: prasus@gmail.com
