apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psmonit.fullname" . }} 
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psmonit.labels" . | nindent 4 }}
data:
  run.sh: {{ tpl (.Files.Get "run.sh") . | b64enc | quote }}
