apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "psmonit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psmonit.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "psmonit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "psmonit.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "psmonit.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: bitnami/kubectl
          command: ["/monitor-script/run.sh"]
          env:
            - name: "cluster"
              value: {{ required "Name of the cluster is required" .Values.cluster }}
            - name: "slackurl"
              value: {{ required "Slack webhook url is required"  .Values.slackurl }}
            - name: "namespace"
              value: {{ required "Jupyter deployment namespace is required"  .Values.ns }}
            - name: "processlist"
              value: {{ required "process list is required, eg: bash|tini|netpyne"  .Values.processlist }}
            - name: "processcount"
              value: {{ required "process count is required"  .Values.processcount }}
          volumeMounts:
            - name: monitor-script
              mountPath: /monitor-script
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
      volumes:
        - name: monitor-script
          projected:
            defaultMode: 493
            sources:
            - secret:
                name: {{ include "psmonit.fullname" . }} 
