apiVersion: v1
kind: Service
metadata:
  name: {{ include "squid.fullname" . }}
  labels:
    app: {{ template "squid.name" . }}
    chart: {{ template "squid.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP 
  ports:
  ports:
    - port: 3128
      protocol: TCP
      targetPort: 3128
  selector:
    app: {{ template "squid.name" . }}
