---
# Source: psmonit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ch-psmonit
  labels:
    app.kubernetes.io/name: psmonit
---
# Source: psmonit/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ch-psmonit 
  namespace: ch
  labels:
    app.kubernetes.io/name: psmonit
data:
  run.sh: "IyEvYmluL2Jhc2gKd2hpbGUgWyAxIF07CmRvCiAgICBuYW1lc3BhY2U9bmV0cHluZQogICAgd2ViaG9va1VSTD0kc2xhY2t1cmwKICAgIGNsdXN0ZXI9JGNsdXN0ZXIKICAgIHBvZExpc3Q9JChrdWJlY3RsIC1uICRuYW1lc3BhY2UgZ2V0IHBvZHMgLWwgY29tcG9uZW50PXNpbmdsZXVzZXItc2VydmVyIHwgZ3JlcCAtaSBydW5uaW5nIHwgYXdrIHsncHJpbnQgJDEnfSB8IHRlZSAvdG1wL3BvZHMucnVubmluZykKICAgIAogICAgZm9yIHBvZCBpbiAkKGNhdCAvdG1wL3BvZHMucnVubmluZykKICAgIGRvCiAgICAgICAga3ViZWN0bCAtbiAkbmFtZXNwYWNlIGV4ZWMgLWl0ICRwb2QgLS0gcHMgLWVvIGNvbW0gfCBncmVwIC1FdmkgJ2NvbW1hbmR8cHN8Z3JlcCcgPiAvdG1wL3Byb2Nlc3MubGlzdAogICAgICAgIHByb2Nlc3NfY291bnQ9JCh3YyAtbCAvdG1wL3Byb2Nlc3MubGlzdCB8IGN1dCAtZCcgJyAtZjEpCiAgICAgICAgaWYgWyAkcHJvY2Vzc19jb3VudCAtZ3QgNSBdCiAgICAgICAgdGhlbgogICAgICAgICAgICBwb3N0RGF0YT0iQUxFUlQ6IFVuZXhwZWN0ZWQgbnVtYmVyIG9mIHByb2Nlc3MgZm91bmQgaW4gcG9kICRwb2QiCiAgICAgICAgICAgIGN1cmwgLVggUE9TVCAtSCAiQ29udGVudC10eXBlOiBhcHBsaWNhdGlvbi9qc29uIiAtLWRhdGEgIntcInRleHRcIjogXCIke3Bvc3REYXRhfVwifSIgJHdlYmhvb2tVUkwKICAgICAgICAgICAgc2xlZXAgMTVtCiAgICAgICAgZmkKICAgICAgICBncmVwIC1FdmkgJ3Rpbml8cHl0aG9ufGJhc2h8bmV0cHluZScgL3RtcC9wcm9jZXNzLmxpc3QKICAgICAgICBpZiBbICQ/IC1lcSAwIF0KICAgICAgICB0aGVuCiAgICAgICAgICAgIHBvc3REYXRhPSJBTEVSVDogVW5leHBlY3RlZCBwcm9jZXNzIGZvdW5kIGluIHBvZCAkcG9kIgogICAgICAgICAgICBjdXJsIC1YIFBPU1QgLUggIkNvbnRlbnQtdHlwZTogYXBwbGljYXRpb24vanNvbiIgLS1kYXRhICJ7XCJ0ZXh0XCI6IFwiJHtwb3N0RGF0YX1cIn0iICR3ZWJob29rVVJMCiAgICAgICAgICAgIHNsZWVwIDE1bQogICAgICAgIGZpCiAgICBkb25lCmRvbmUK"
---
# Source: psmonit/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ch-psmonit 
  namespace: ch
  labels:
    app.kubernetes.io/name: psmonit
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
# Source: psmonit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ch-psmonit
  namespace: ch
  labels:
    app.kubernetes.io/name: psmonit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ch-psmonit
subjects:
- kind: ServiceAccount
  name: ch-psmonit
  namespace: ch
---
# Source: psmonit/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-psmonit
  namespace: ch
  labels:
    app.kubernetes.io/name: psmonit
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: psmonit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psmonit
    spec:
      serviceAccountName: ch-psmonit
      containers:
        - name: psmonit
          image: bitnami/kubectl
          command: ["/monitor-script/run.sh"]
          env:
            - name: "cluster"
              value: ecas2 
            - name: "slackurl"
              value: slack 
          volumeMounts:
            - name: monitor-script
              mountPath: /monitor-script
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
      volumes:
        - name: monitor-script
          projected:
            defaultMode: 493
            sources:
            - secret:
                name: ch-psmonit
