---
# Source: psmonit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-psmonit
  labels:
    app.kubernetes.io/name: psmonit
---
# Source: psmonit/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-psmonit 
  namespace: monitoring
  labels:
    app.kubernetes.io/name: psmonit
data:
  run.sh: "IyEvYmluL2Jhc2gKd2hpbGUgWyAxIF07CmRvCiAgICBuYW1lc3BhY2U9JG5zCiAgICB3ZWJob29rVVJMPSRzbGFja3VybAogICAgY2x1c3Rlcj0kY2x1c3RlcgogICAgcG9kTGlzdD0kKGt1YmVjdGwgLW4gJG5hbWVzcGFjZSBnZXQgcG9kcyAtbCBjb21wb25lbnQ9c2luZ2xldXNlci1zZXJ2ZXIgfCBncmVwIC1pIHJ1bm5pbmcgfCBhd2sgeydwcmludCAkMSd9IHwgdGVlIC90bXAvcG9kcy5ydW5uaW5nKQogICAgCiAgICBmb3IgcG9kIGluICQoY2F0IC90bXAvcG9kcy5ydW5uaW5nKQogICAgZG8KICAgICAgICBrdWJlY3RsIC1uICRuYW1lc3BhY2UgZXhlYyAtaXQgJHBvZCAtLSBwcyAtZW8gY29tbSB8IGdyZXAgLUV2aSAnY29tbWFuZHxwc3xncmVwJyA+IC90bXAvcHJvY2Vzcy5saXN0CiAgICAgICAgcHJvY2Vzc19jb3VudD0kKHdjIC1sIC90bXAvcHJvY2Vzcy5saXN0IHwgY3V0IC1kJyAnIC1mMSkKICAgICAgICBpZiBbICRwcm9jZXNzX2NvdW50IC1ndCA1IF0KICAgICAgICB0aGVuCiAgICAgICAgICAgIHBvc3REYXRhPSI6cmVkX2NpcmNsZTogdW5leHBlY3RlZCBtdW1iZXIgb2YgcHJvY2Vzc2VzIGluICRjbHVzdGVyIGNsdXN0ZXIsIHBvZDogJHBvZCIKICAgICAgICAgICAgY3VybCAtWCBQT1NUIC1IICJDb250ZW50LXR5cGU6IGFwcGxpY2F0aW9uL2pzb24iIC0tZGF0YSAie1widGV4dFwiOiBcIiR7cG9zdERhdGF9XCJ9IiAkd2ViaG9va1VSTAogICAgICAgICAgICBzbGVlcCAxNW0KICAgICAgICBmaQogICAgICAgIGdyZXAgLUV2aSAndGluaXxweXRob258YmFzaHxuZXRweW5lJyAvdG1wL3Byb2Nlc3MubGlzdAogICAgICAgIGlmIFsgJD8gLWVxIDAgXQogICAgICAgIHRoZW4KICAgICAgICAgICAgcG9zdERhdGE9IjpyZWRfY2lyY2xlOiB1bmV4cGVjdGVkIHByb2Nlc3MgaW4gJGNsdXN0ZXIgY2x1c3RlciwgcG9kOiAkcG9kIgoJICAgIGN1cmwgLVggUE9TVCAtSCAiQ29udGVudC10eXBlOiBhcHBsaWNhdGlvbi9qc29uIiAtLWRhdGEgIntcInRleHRcIjogXCIke3Bvc3REYXRhfVwifSIgJHdlYmhvb2tVUkwKICAgICAgICAgICAgc2xlZXAgMTVtCiAgICAgICAgZmkKICAgIGRvbmUKZG9uZQo="
---
# Source: psmonit/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-psmonit 
  namespace: monitoring
  labels:
    app.kubernetes.io/name: psmonit
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
# Source: psmonit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-psmonit
  namespace: monitoring
  labels:
    app.kubernetes.io/name: psmonit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-psmonit
subjects:
- kind: ServiceAccount
  name: test-psmonit
  namespace: monitoring
---
# Source: psmonit/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-psmonit
  namespace: monitoring
  labels:
    app.kubernetes.io/name: psmonit
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: psmonit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psmonit
    spec:
      serviceAccountName: test-psmonit
      containers:
        - name: psmonit
          image: bitnami/kubectl
          #command: ["/monitor-script/run.sh"]
          command: ["sleep", "360"]
          env:
            - name: "cluster"
              value: ecas2:cluster-1 
            - name: "slackurl"
              value: https://hooks.slack.com/services/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 
            - name: "namespace"
              value: netpyne 
          volumeMounts:
            - name: monitor-script
              mountPath: /monitor-script
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
      volumes:
        - name: monitor-script
          projected:
            defaultMode: 493
            sources:
            - secret:
                name: test-psmonit
